# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Description is in document head meta (for Google search results) and in your feed.xml site description

# Site settings
title: Tech, Mountains, Love, &etc.
email: clint+blog@ctro.net
description: > # this means to ignore newlines until "baseurl:"
  I'm Clint Troxel. I work for 18F. I like simplicity.
  I live in Jackson, WY. I Love my family, the mountains, and you.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ctro.net" # the base hostname & protocol for your site
twitter_username:
github_username:  ctro

# Build settings
markdown: kramdown
